# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5d13611dddd5198f2d7f595bc73fa3a37379a234af73982f267b92a63535fa5949d8ead6cde3af45fd0a54001ea601d8c52a65001e3b8b7e3000a47c17f8d94

test:
  secret_key_base: 6ecb90daba01330045c5178951295c39ce2e11ecff772bb2850c2430fa613b958d6fc96e7a96cc451dc9c7d4b78b362849005d95c4a974306005afeab034d3c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
